# Defaults tasks for role mailman
---
- name: Download jekyll-theme-centos data files into defaults
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ role_path }}/defaults/"
    remote_src: true
  loop:
    - https://gitlab.com/CentOS/artwork/centos-web/jekyll-theme-centos-navbar/-/archive/{{ site_navbar_version }}/jekyll-theme-centos-navbar-{{ site_navbar_version }}.tar.gz
    - https://gitlab.com/CentOS/artwork/centos-web/jekyll-theme-centos-identity/-/archive/{{ site_identity_version }}/jekyll-theme-centos-identity-{{ site_identity_version }}.tar.gz
    - https://gitlab.com/CentOS/artwork/centos-web/jekyll-theme-centos-footer/-/archive/{{ site_footer_version }}/jekyll-theme-centos-footer-{{ site_footer_version }}.tar.gz
  delegate_to: localhost
  become: false
  tags:
    - theme

- name: pkgs should be installed for mailman
  yum:
    name: ['mailman', 'patch']
    state: latest

- name: MailMan config
  template:
    src: mm_cfg.py.j2
    dest: /etc/mailman/mm_cfg.py
    mode: 0644
  notify:
    - restart_mailman
  tags:
    - config

- name: Ensuring with have a mailman admin pass
  shell: "/usr/lib/mailman/bin/mmsitepass {{ mailman_admin_pass }}"
  args:
    creates: /etc/mailman/adm.pw
  no_log: True

- name: Ensuring we can drop mailman list configs
  file:
    path: /etc/mailman/list_configs
    state: directory
    mode: 0750
  tags:
    - lists

- name: Gather current mailman lists as facts
  mailman_lists:
  tags:
    - lists

- name: Creating default mailman list if needed
  command: "/usr/lib/mailman/bin/newlist -q Mailman {{ mailman_admin }} {{ mailman_admin_pass }}"
  when: "'mailman' not in mailman.lists"
  register: mailman_sitelist

- name: Configuring default mailman sitelist
  command: "/usr/lib/mailman/bin/config_list -i /etc/mailman/sitelist.cfg mailman"
  when: mailman_sitelist is changed

- name: Creating lists if needed
  command: "/usr/lib/mailman/bin/newlist -q {{ item.name | lower }} {{ item.admin }} {{ item.password }}"
  when: "item.name|lower not in mailman.lists"
  with_items: "{{ mailman_lists }}"
  loop_control:
    label: '{{ item.name }}'
  tags:
    - lists

- name: Creating list settings
  template:
    src: list-settings.cfg.j2
    dest: "/etc/mailman/list_configs/{{ item.name | lower }}-settings.cfg"
    mode: 0644
  with_items: "{{ mailman_lists }}"
  loop_control:
    label: '{{ item.name }}'
  register: list_settings  
  tags:
    - lists

- name: Configuring list when changed
  command: "/usr/lib/mailman/bin/config_list -i /etc/mailman/list_configs/{{ item.item.name | lower }}-settings.cfg {{ item.item.name | lower }}"
  with_items: "{{ list_settings.results }}"
  when: item.changed
  loop_control:
    label: '{{ item.item.name }}'
  tags:
    - lists

- name: Importing mailman templates
  template:
    src: "{{ item }}"
    dest: "/etc/mailman/templates/en/"
  loop: "{{ lookup('fileglob', 'templates/etc/mailman/templates/en/*', wantlist=True) }}"
  register: templates_import
  notify: restart_mailman
  tags:
    - theme

- name: Patching mailman for our templates
  patch:
    src: "patches/{{ item }}"
    basedir: /
  with_items:
    - mm-cgi-auth.py.patch
    - "{{ ansible_facts.distribution }}{{ ansible_facts.distribution_major_version }}-mm-htmlformat.py.patch"
  tags:
    - patch

- name: Configuring recaptcha if needed
  include_tasks: recaptcha.yml
  when: mailman_recaptcha

- name: Configuring selinux
  include_tasks: selinux.yml

- name: Configuring httpd
  include_tasks: httpd.yml
  tags:
    - tls

- name: Update archives to apply template changes
  shell: "/usr/lib/mailman/bin/arch {{ item.name | lower }} || true"
  when: templates_import.changed
  with_items: "{{ mailman_lists }}"
  loop_control:
    label: '{{ item.name }}'
  tags:
    - theme

- name: mailman should be started and enabled
  service:
    name: mailman
    state: started
    enabled: True

- name: Ensuring backup user and jobs
  include_role:
    name: centos-backup
    tasks_from: client
  vars:
    - centos_role: mailman
    - role_backup_folders:
        - /var/lib/mailman
  tags:
    - backup
